package cr.ac.una.progra4.deddrivers.domain;
// Generated 03/11/2017 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer idServicio;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private String puntoLlegada;
     private String puntoSalida;
     private String horaLlegada;
     private String horaSalida;
     private int duracion;
     private Float costo;
     private int idRetroalimentacion;
     private Date fechaRealizado;
     private Integer puntuacion;
     private String comentario;
     private String ultimoUsuario;
     private Date ultimaFecha;

    public Servicio() {
    }

	
    public Servicio(Usuario usuario, Vehiculo vehiculo, int duracion, int idRetroalimentacion) {
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.duracion = duracion;
        this.idRetroalimentacion = idRetroalimentacion;
    }
    public Servicio(Usuario usuario, Vehiculo vehiculo, String puntoLlegada, String puntoSalida, String horaLlegada, String horaSalida, int duracion, Float costo, int idRetroalimentacion, Date fechaRealizado, Integer puntuacion, String comentario, String ultimoUsuario, Date ultimaFecha) {
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.puntoLlegada = puntoLlegada;
       this.puntoSalida = puntoSalida;
       this.horaLlegada = horaLlegada;
       this.horaSalida = horaSalida;
       this.duracion = duracion;
       this.costo = costo;
       this.idRetroalimentacion = idRetroalimentacion;
       this.fechaRealizado = fechaRealizado;
       this.puntuacion = puntuacion;
       this.comentario = comentario;
       this.ultimoUsuario = ultimoUsuario;
       this.ultimaFecha = ultimaFecha;
    }
   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getPuntoLlegada() {
        return this.puntoLlegada;
    }
    
    public void setPuntoLlegada(String puntoLlegada) {
        this.puntoLlegada = puntoLlegada;
    }
    public String getPuntoSalida() {
        return this.puntoSalida;
    }
    
    public void setPuntoSalida(String puntoSalida) {
        this.puntoSalida = puntoSalida;
    }
    public String getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(String horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }
    public Float getCosto() {
        return this.costo;
    }
    
    public void setCosto(Float costo) {
        this.costo = costo;
    }
    public int getIdRetroalimentacion() {
        return this.idRetroalimentacion;
    }
    
    public void setIdRetroalimentacion(int idRetroalimentacion) {
        this.idRetroalimentacion = idRetroalimentacion;
    }
    public Date getFechaRealizado() {
        return this.fechaRealizado;
    }
    
    public void setFechaRealizado(Date fechaRealizado) {
        this.fechaRealizado = fechaRealizado;
    }
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }




}


